apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
spec:
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
        - name: jaeger
          image: jaegertracing/all-in-one:latest
          ports:
            - containerPort: 5775
            - containerPort: 6831
            - containerPort: 6832
            - containerPort: 5778
            - containerPort: 16686
            - containerPort: 14268
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger
spec:
  selector:
    app: jaeger
  ports:
    - port: 5775
      targetPort: 5775
      protocol: UDP
      name: upd01
    - port: 6831
      targetPort: 6831
      protocol: UDP
      name: udp02
    - port: 6832
      targetPort: 6832
      protocol: UDP
      name: udp03
    - port: 5778
      targetPort: 5778
      protocol: TCP
      name: tcp01
    - port: 16686
      targetPort: 16686
      protocol: TCP
      name: tcp02
    - port: 14268
      targetPort: 14268
      protocol: TCP
      name: tcp03