apiVersion: apps/v1
kind: Deployment
metadata:
  name: ledgerservice
spec:
  selector:
    matchLabels:
      app: ledgerservice
  replicas: 1 # since replicas would need mongodb to manage data TODO: volume
  template:
    metadata:
      labels:
        app: ledgerservice
    spec:
      containers:
        - name: ledgerservice
          image: mimirssource/ledgerservice:1.0
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ledgerservice
spec:
  selector:
    app: ledgerservice
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP